chat/urls.py
from django.urls import path

from .views import new_chat_view, inbox_view, detail_view

app_name = "chat"

urlpatterns = [
    path("", inbox_view, name="inbox"),
    path("<int:pk>/", detail_view, name="detail"),
    path("new/<int:item_pk>/", new_chat_view, name="new")
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import LoginFrom
from .views import (
    index_view, 
    contact_view,
    signup_view
)

app_name = "core"

urlpatterns = [
    path("", index_view, name="index"),
    path("contact/", contact_view, name="contact"),
    path("signup/", signup_view, name="signup"),
    path("login/", auth_views.LoginView.as_view(
        authentication_form=LoginFrom,
        template_name="core/login.html"
    ), name="login")
]

dashboard/urls.py
from django.urls import path

from .views import index_view

app_name = "dashboard"

urlpatterns = [
    path("", index_view, name="index")
]

item/urls.py
from django.urls import path

from .views import (
    detail_view, new_view, delete_view, edit_view, items_view
)

app_name = "item"

urlpatterns = [
    path("", items_view, name="items"),
    path("new/", new_view, name="new"),
    path("<int:pk>/", detail_view, name="detail"),
    path("<int:pk>/delete/", delete_view, name="delete"),
    path("<int:pk>/edit/", edit_view, name="edit"),
]

shuffle/urls.py
"""
Django should not serve static content, i.e. 
static or media files. Some other, like nginx, apache, etc. 
should serve static content in production environment.
"""
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("core.urls")),
    path("items/", include("item.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("inbox/", include("chat.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    price = models.FloatField()
    is_sold = models.BooleanField(default=False)
    image = models.ImageField(upload_to="item_images")
    #  related_name for reverse relation
    created_by = models.ForeignKey(User, related_name="items", on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name="items", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginFrom(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Your username",
        "class": "w-full py-2 px-3 rounded-lg"
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Your password",
        "class": "w-full py-2 px-3 rounded-lg"
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Your username",
        "class": "w-full py-2 px-3 rounded-lg"
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        "placeholder": "Your email address",
        "class": "w-full py-2 px-3 rounded-lg"
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Your password",
        "class": "w-full py-2 px-3 rounded-lg"
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Repeat password",
        "class": "w-full py-2 px-3 rounded-lg"
    }))

core/views.py
from django.shortcuts import render, redirect
from .models import Item, Category
from .forms import SignupForm

def index_view(request):
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    context = {
        "items": items,
        "categories": categories
    }
    return render(request, "core/index.html", context)

def contact_view(request):
    return render(request, "core/contact.html")

def signup_view(request):
    if request.method == "POST":
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            
            return redirect("login/")
    else:
        form = SignupForm()

    context = {
        "form": form
    }

    return render(request, "core/signup.html", context)

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- tailwind -->
        <script src="https://cdn.tailwindcss.com"></script>
        <title>{% block title %} {% endblock %} - Shuffle</title>
    </head>
    <body>
        <!-- Nav -->
        <nav class="px-4 py-4 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-lg font-semibold">Shuffle</a>
            <div class="space-x-4">
                <a href="{% url 'item:new' %}" class="font-semibold hover:text-gray-500">New Item</a>
                <a href="{% url 'item:items' %}" class="font-semibold hover:text-gray-500">Explore</a>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'chat:inbox' %}" class="font-semibold px-3 py-2 bg-teal-500 text-white rounded hover:bg-teal-700">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="font-semibold px-3 py-2 bg-gray-500 text-white rounded hover:bg-gray-700">Dashboard</a>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="font-semibold px-3 py-2 bg-gray-500 text-white rounded hover:bg-gray-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="font-semibold px-3 py-2 bg-sky-500 text-white rounded hover:bg-sky-700">Sign in</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <!-- Footer -->
        <footer class="px-4 py-4 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>
                <p class="text-gray-500">
                    An online marketplace for buying and selling.
                </p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Links</h3>
                <ul class="space-y-2">
                    <li><a href="#" class="text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-teal-500 hover:text-teal-700">Privacy</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

core/templates/core/contact.html
{% extends "core/base.html" %}

{% block title %}
    Contact
{% endblock %}

{% block content %}
    <h1>Contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %}
    Welcome
{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center"> New Products </h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" alt="{{ item.name }}" class="rounded-t-lg">
                        </div>

                        <div class="p-6 bg-white rounded-b-lg">
                            <h2 class="text-lg">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <!-- Category -->

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center"> Category </h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
            <div>
                <a href="#">
                     <div class="p-6 bg-white rounded-b-lg">
                        <h2 class="text-lg">{{ category.name }}</h2>
                        <p class="text-gray-500">{{ category.items.count }} items</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends "core/base.html" %}
{% block title %} Sign in {% endblock %}


{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-lg">
        <h1 class="mb-6 text-3xl">Sign in</h1>
        <form method="post" action="." >
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br/>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br/>
                {{ form.password }}
            </div>
            
            <!-- error handling -->
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-lg">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="py-2 px-4 mt-2 bg-teal-500 hover:bg-teal-700 rounded-lg text-white">Submit</button>
        </form>
    </div>
{% endblock %}

core/templates/core/signup.html
{% extends "core/base.html" %}
{% block title %} Sign up {% endblock %}


{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-lg">
        <h1 class="mb-6 text-3xl">Sign up</h1>
        <form method="post" action="." >
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br/>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br/>
                {{ form.email }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br/>
                {{ form.password1 }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Repeat password</label><br/>
                {{ form.password2 }}
            </div>
            
            <!-- error handling -->
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-lg">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="py-2 px-4 mt-2 bg-teal-500 hover:bg-teal-700 rounded-lg text-white">
                Submit
            </button>
        </form>
    </div>
{% endblock %}