chat/urls.py
from django.urls import path

from .views import new_chat_view, inbox_view, detail_view

app_name = "chat"

urlpatterns = [
    path("", inbox_view, name="inbox"),
    path("<int:pk>/", detail_view, name="detail"),
    path("new/<int:item_pk>/", new_chat_view, name="new")
]

item/urls.py
from django.urls import path

from .views import (
    detail_view, new_view, delete_view, edit_view, items_view
)

app_name = "item"

urlpatterns = [
    path("", items_view, name="items"),
    path("new/", new_view, name="new"),
    path("<int:pk>/", detail_view, name="detail"),
    path("<int:pk>/delete/", delete_view, name="delete"),
    path("<int:pk>/edit/", edit_view, name="edit"),
]

shuffle/urls.py
"""
Django should not serve static content, i.e. 
static or media files. Some other, like nginx, apache, etc. 
should serve static content in production environment.
"""
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("core.urls")),
    path("items/", include("item.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("inbox/", include("chat.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/forms.py
from django import forms
from core.models import Item

INPUT_CLASSES = "w-full py-2 px-3 rounded-lg border"

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["category", "name", "description", "price", "image"]
        widgets = {
            "category": forms.Select(attrs={
                "class": INPUT_CLASSES
            }),
            "name": forms.TextInput(attrs={
                "class": INPUT_CLASSES
            }),
            "description": forms.Textarea(attrs={
                "class": INPUT_CLASSES
            }),
            "price": forms.TextInput(attrs={
                "class": INPUT_CLASSES
            }),
            "image": forms.FileInput(attrs={
                "class": INPUT_CLASSES
            })
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["name", "description", "price", "image", "is_sold"]
        widgets = {
            "name": forms.TextInput(attrs={
                "class": INPUT_CLASSES
            }),
            "description": forms.Textarea(attrs={
                "class": INPUT_CLASSES
            }),
            "price": forms.TextInput(attrs={
                "class": INPUT_CLASSES
            }),
            "image": forms.FileInput(attrs={
                "class": INPUT_CLASSES
            })
        }

item/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q

from .forms import NewItemForm, EditItemForm
from core.models import Item, Category

def items_view(request):
    items = Item.objects.filter(is_sold=False)
    query = request.GET.get("query", "") # Default is empty/""
    categories = Category.objects.all()
    category_id = request.GET.get("category", 0)

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    context = {
        "items": items,
        "query": query,
        "categories": categories,
        "category_id": int(category_id)
    }
    return render(request, "item/items.html", context=context)

def detail_view(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]
    
    context = {
        "related_items": related_items,
        "item": item
    }
    return render(request, "item/detail.html", context)

@login_required
def new_view(request):
    if request.method == "POST":
        form = NewItemForm(request.POST, request.FILES) # file to be uploaded
        if form.is_valid():
            item = form.save(commit=False) # don't commit changes to db. Just create object
            item.created_by = request.user # need to add created_by before adding to db
            item.save() # commit to db
            return redirect("item:detail", pk=item.id)
    else:
        form = NewItemForm()
    context = {
        "form": form,
        "title": "New item"
    }
    return render(request, "item/form.html", context)

@login_required
def edit_view(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)

    if request.method == "POST":
        form = EditItemForm(request.POST, request.FILES, instance=item) # file to be uploaded
        if form.is_valid():
            form.save()
            return redirect("item:detail", pk=item.id)
    else:
        form = EditItemForm(instance=item) # so the form isn't empty
    context = {
        "form": form,
        "title": "Edit item"
    }
    return render(request, "item/form.html", context)

@login_required
def delete_view(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect("dashboard:index")

item/templates/item/detail.html
{% extends "core/base.html" %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.image.url }}" alt="{{item.name}}" class="rounded-xl">
    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        <p class="text-gray-500 p-3"><strong>Price:</strong> {{ item.price }}</p>
        <p class="text-gray-500 p-3"><strong>Seller:</strong> {{ item.created_by }}</p>
        <p class="text-gray-500 p-3"><strong>Published:</strong> {{ item.created_at|date:"M d Y" }}</p>
        {% if item.description %}
            <p class="text-gray-700 p-3">
                <strong class="text-gray-500">Description:</strong><br/>
                {{ item.description }}
            </p>
        {% endif %}

        {% if request.user == item.created_by %}
            <div class="mt-4 p-4 bg-white rounded-lg">
                <p>This is your item</p>          
                <a href="{% url 'item:edit' item.id %}" class="inline-block mt-4 px-4 py-2 text-lg font-semibold bg-teal-500 text-white rounded-lg">Edit</a> 
                <a href="{% url 'item:delete' item.id %}" class="inline-block mt-4 px-4 py-2 text-lg font-semibold bg-red-500 text-white rounded-lg">Delete</a> 
            </div>
        {% else %}
            <a href="{% url 'chat:new' item.id %}" class="inline-block mt-6 px-6 py-3 font-semibold bg-sky-500 text-white hover:bg-sky-700 rounded-lg">Contact Seller</a>
        {% endif %}
    </div>
</div>

<!-- related products -->
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center"> Related products </h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in related_items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" alt="{{ item.name }}" class="rounded-t-lg">
                    </div>

                    <div class="p-6 bg-white rounded-b-lg">
                        <h2 class="text-lg">{{ item.name }}</h2>
                        <p class="text-gray-500">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

item/templates/item/form.html
{% extends "core/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<!-- enctype="multipart/form-data" to upload images -->
<form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-lg">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <button class="mt-6 py-2 px-4 mt-2 bg-teal-500 hover:bg-teal-700 rounded-lg text-white">Submit</button>

</form>
{% endblock %}

item/templates/item/items.html
{% extends "core/base.html" %}

{% block title %} Explore {% endblock %}

{% block content %}
    <div class="p-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form action="{% url 'item:items' %}" method="get">
                <input type="text" name="query" value="{{ query }}" placeholder="Find items" class="w-full py-2 px-4 border rounded-xl">
                <button class="mt-2 py-2 px-4 bg-teal-500 text-white rounded-xl">Search</button>
            </form>

            <hr class="my-6">
            <p class="font-semibold">Catagory</p>

            <ul class="mt-4">
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl {% if category.id == category_id %} bg-gray-300 {% endif %}">
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>

        </div>

        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% for item in items %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div>
                                <img src="{{ item.image.url }}" alt="{{ item.name }}" class="rounded-t-lg">
                            </div>
    
                            <div class="p-6 bg-white rounded-b-lg">
                                <h2 class="text-lg">{{ item.name }}</h2>
                                <p class="text-gray-500">Price: {{ item.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}